name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.12.9
        
    - name: Build
      run: |
        echo $Qt5_DIR
        export PATH=$Qt5_DIR/bin:$PATH
        qmake --version
        mkdir build && cd build
        qmake ../qt-subdirs-project-sample.pro
        make
